name: flutter_arb_translator
description: A command line tool which simplifies translation of Flutter ARB files.
version: 1.0.10
homepage: https://github.com/sxtfv/flutter_arb_translator

environment:
  sdk: '>=2.16.1 <4.0.0'

dependencies:
   http: ^1.1.0
   path: ^1.8.3
   encrypt: ^5.0.1
   pointycastle: ^3.7.3
   args: ^2.4.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.24.6
