name: flutter_arb_translator
description: A command line tool which simplifies translation of Flutter ARB files.
version: 1.0.6
homepage: https://github.com/sxtfv/flutter_arb_translator

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
   http: ^0.13.4
   path: ^1.8.0
   encrypt: ^5.0.1
   pointycastle: ^3.5.2
   args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
